Repository pagopa/pagopa-platform-authorizer, pull requests merged in 2023-05, with the labels that each got.

#3 [PAGOPA-859] multi-entity subscription key authorizer
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  .github/workflows/code_review.yml
  .gitignore
  Dockerfile
  helm/.helmignore
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/run_integration_test.sh
  integration-test/src/README.md
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/main.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/support/clients/payments_client.js
  integration-test/src/step_definitions/support/logic/common_logic.js
  integration-test/src/step_definitions/support/steps.js
  integration-test/src/step_definitions/support/utility/axios_common.js
  integration-test/src/step_definitions/support/utility/helpers.js
  integration-test/src/yarn.lock
  pom.xml
  src/main/java/it/gov/pagopa/authorizer/CacheGenerator.java
  src/main/java/it/gov/pagopa/authorizer/CacheNotifier.java
  src/main/java/it/gov/pagopa/authorizer/Info.java
  src/main/java/it/gov/pagopa/authorizer/entity/SubscriptionKeyDomain.java
  src/main/java/it/gov/pagopa/authorizer/service/CacheService.java
  src/main/java/it/gov/pagopa/authorizer/service/DataAccessObject.java
  src/main/java/it/gov/pagopa/authorizer/util/Constants.java
  src/test/java/it/gov/pagopa/authorizer/CacheGeneratorFunctionTest.java
  src/test/java/it/gov/pagopa/authorizer/CacheNotifierFunctionTest.java
  src/test/java/it/gov/pagopa/authorizer/InfoFunctionTest.java
  src/test/java/it/gov/pagopa/authorizer/service/CacheServiceTest.java
  src/test/java/it/gov/pagopa/authorizer/service/DataAccessObjectTest.java
Labels: bug

#4 fix: changed poolImage reference
  .devops/deploy-pipelines.yml
Labels: ignore-for-release

#5 [PagoPa-928] Enrolled EC
  local.settings.json.example
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/authorizer/EnrolledEC.java
  src/test/java/it/gov/pagopa/authorizer/EnrolledEcTest.java
Labels: enhancement

#6 [PAGOPA-929] enrolled ec integration test
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/main.feature
  integration-test/src/step_definitions/support/clients/enrolled_ec_client.js
  integration-test/src/step_definitions/support/logic/common_logic.js
  integration-test/src/step_definitions/support/steps.js
  openapi/openapi.json
  pom.xml
Labels: enhancement
